### ISSUE TITLE
`left__heading` linklariga hover va active holatlarini qo'shish kerak

### ISSUE THREAD

**Issue by darxanov** [Andarov/job-list#1]
Sizdagi holat: 
![image](https://user-images.githubusercontent.com/99054718/167868984-58aee0f0-2638-4d9d-b359-62891837d46e.png)

Maketdagi holat: 
![image](https://user-images.githubusercontent.com/99054718/167868923-b2772bdb-b84d-4622-a021-fe5bdcb86be2.png)

**Comment by Andarov** [comment]
#1
